-- MySQL Script generated by MySQL Workbench
-- Thu Aug 29 15:49:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_clinicaEstetica
-- -----------------------------------------------------
-- O banco de dados é utilizado para guardar os registros e dados do login de uma clinica de estética
-- 
-- Nome:Eduardo Rafael Pires de Mendonça
-- Data:15/08/2019

-- -----------------------------------------------------
-- Schema bd_clinicaEstetica
--
-- O banco de dados é utilizado para guardar os registros e dados do login de uma clinica de estética
-- 
-- Nome:Eduardo Rafael Pires de Mendonça
-- Data:15/08/2019
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_clinicaEstetica` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `bd_clinicaEstetica` ;

-- -----------------------------------------------------
-- Table `bd_clinicaEstetica`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_clinicaEstetica`.`clientes` (
  `cpf` VARCHAR(15) NOT NULL COMMENT 'CPF do cliente como chave primaria.',
  `nome` VARCHAR(45) NOT NULL COMMENT 'Vai pegar o nome completo do Cliente.',
  `dataNasc` DATE NOT NULL COMMENT 'Pegar a data de nascimento do cliente.',
  `telefone` VARCHAR(15) NOT NULL COMMENT 'Pegar o telefone do cliente.',
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
COMMENT = 'Vai pegar todos os registros do clientes para ser armazenados.';


-- -----------------------------------------------------
-- Table `bd_clinicaEstetica`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_clinicaEstetica`.`usuarios` (
  `cpf` VARCHAR(15) NOT NULL COMMENT 'Vai pegar o CPF do proprietário para fazer o login.',
  `senha` VARCHAR(32) NOT NULL COMMENT 'Vai pegar a senha do proprietário para o login.',
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
COMMENT = 'Vai pegar os dados dos proprietarios para poder fazer o login.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
